//go:build !ignore_autogenerated

/*
Copyright 2026 The Understudy Authors.
Modifications Copyright 2026 The PodHandoff Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHandoff) DeepCopyInto(out *PodHandoff) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHandoff.
func (in *PodHandoff) DeepCopy() *PodHandoff {
	if in == nil {
		return nil
	}
	out := new(PodHandoff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodHandoff) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHandoffList) DeepCopyInto(out *PodHandoffList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodHandoff, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHandoffList.
func (in *PodHandoffList) DeepCopy() *PodHandoffList {
	if in == nil {
		return nil
	}
	out := new(PodHandoffList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodHandoffList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHandoffSpec) DeepCopyInto(out *PodHandoffSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.SurgeReplicas != nil {
		in, out := &in.SurgeReplicas, &out.SurgeReplicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadinessDeadlineSeconds != nil {
		in, out := &in.ReadinessDeadlineSeconds, &out.ReadinessDeadlineSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MinSurgeTimeSeconds != nil {
		in, out := &in.MinSurgeTimeSeconds, &out.MinSurgeTimeSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHandoffSpec.
func (in *PodHandoffSpec) DeepCopy() *PodHandoffSpec {
	if in == nil {
		return nil
	}
	out := new(PodHandoffSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodHandoffStatus) DeepCopyInto(out *PodHandoffStatus) {
	*out = *in
	if in.LastSurgeTime != nil {
		in, out := &in.LastSurgeTime, &out.LastSurgeTime
		*out = (*in).DeepCopy()
	}
	if in.LastReleaseTime != nil {
		in, out := &in.LastReleaseTime, &out.LastReleaseTime
		*out = (*in).DeepCopy()
	}
	if in.BlockedSince != nil {
		in, out := &in.BlockedSince, &out.BlockedSince
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodHandoffStatus.
func (in *PodHandoffStatus) DeepCopy() *PodHandoffStatus {
	if in == nil {
		return nil
	}
	out := new(PodHandoffStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetReference) DeepCopyInto(out *TargetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetReference.
func (in *TargetReference) DeepCopy() *TargetReference {
	if in == nil {
		return nil
	}
	out := new(TargetReference)
	in.DeepCopyInto(out)
	return out
}
